apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: auth-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
