services:
  authentication.api:
    container_name: authentication.api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_HTTP_PORTS=${ASPNETCORE_HTTP_PORTS}
      - ConnectionStrings__Default=${AUTH_DB_CONNECTION_STRING}
      - USER_SECRETS_ID=${USER_SECRETS_ID}
    ports:
      - "${AUTH_API_PORT}:${ASPNETCORE_HTTP_PORTS}"
    volumes:
      - ${USER_SECRETS_HOST_PATH}:${USER_SECRETS_CONTAINER_PATH}
  
  auth.db:
    container_name: auth.db
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${AUTH_DB_VOLUME}:/var/lib/postgresql/data
  
  learning.db:
    container_name: learning.db
    restart: always
    ports:
      - "${LEARNING_DB_PORT}:27017"
    volumes:
      - ${LEARNING_DB_VOLUME}:/data/db

  mongo-ui:
    container_name: mongo-ui
    restart: always
    ports:
      - "${MONGO_UI_PORT}:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=${MONGO_DB_URL}
      - ME_CONFIG_BASICAUTH=${MONGO_UI_AUTH}
    profiles:
      - development