services:
  authentication.api:
    image: authentication.api
    build:
      context: .
      dockerfile: api/services/authentication/Authentication.API/Dockerfile
  
  auth.db:
    image: postgres
    
volumes:
  auth.db.volume: