apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-api
  template:
    metadata:
      labels:
        app: authentication-api
    spec:
      containers:
        - name: authentication-api
          image: authentication.api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ConnectionStrings__Default
              value: "Host=auth-db;Port=5432;Database=authdb;Username=postgres;Password=postgres"
            - name: NotificationsApi__Http
              value: "http://notifications-api:8080/"
            - name: NotificationsApi__Https
              value: "https://notifications-api:8081/"
            - name: NotificationsApi__IsHttps
              value: "false"
            - name: NotificationsApi__Key
              value: "8F48AA5F-9B1C-4285-9BDC-46052AC176CF"

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-api
spec:
  selector:
    app: authentication-api
  ports:
    - port: 80
      targetPort: 8080
  type: NodePort
